### ISSUE TITLE
About the labels and performance

### ISSUE THREAD

**Issue by cbbjames** [iliaschalkidis/lmtc-eurlex57k#1]
Hi, 

Thanks for the nice dataset and paper.
As emphasizing on large number of labels, do you by chance have a histogram of frequency of labels and per-label performance for a peek?

Thanks,

**Comment by iliaschalkidis** [comment]
Thanks @cbbjames . You may find a histogram in the article https://www.aclweb.org/anthology/W19-2209/. Computing performance per label would be an overkill, as we deal with thousands of labels and it is impossible to track, compare and comment on scores for all these labels. Anyway, you may do that by amending the code (`lmtc.py/calculate_perfomance`) to get per-label precision, recall, f1-score.
