### ISSUE TITLE
Unable to download the dataset

### ISSUE THREAD

**Issue by dhruvdcoder** [iliaschalkidis/lmtc-eurlex57k#12]
The download always stops after 7.48 MB. Is the dataset available in an alternate location?

Thanks!

**Comment by iliaschalkidis** [comment]
Ηι @dhruvdcoder the dataset is here http://nlp.cs.aueb.gr/software_and_datasets/EURLEX57K/

I just tried to download the documents (clicking 'Datasets (Raw Text)') and I had not issue at all. Please let me know, if there is any other issue.

**Comment by dhruvdcoder** [comment]
@iliaschalkidis Thank you for the quick response. I am able to download it now! Not sure why it was not working last night.
