### ISSUE TITLE
run_lmtc.py missing

### ISSUE THREAD

**Issue by dtuggener** [iliaschalkidis/lmtc-eurlex57k#2]
Hello,

I'm trying to run your BERT model (https://github.com/AnonymousXMTC2019/LMTC/tree/master/neural_networks/layers/bert) on a related dataset of labeled legal provisions. This repo seems to be missing the file `run_lmtc.py` which is mentioned in the Readme under "Train Model".

Would you be willing to provide the script to reproduce your experiments with BERT?

Thanks and kind regards

**Comment by ghost** [comment]
All of the code is missing, to be precise. It seems like the updated README (that is, the cleaned-up version of the repository from the anonymity period) is present, but the code itself is not.

**Comment by iliaschalkidis** [comment]
All done! Follow READ_ME and Enjoy!
